<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-T3EO6I8" ignored="0" name="RetryMultipleFailedTestCases" tests="9" failures="2" timestamp="20 Oct 2018 13:59:41 GMT" time="0.102" errors="0">
  <testcase name="Test1" time="0.017" classname="mytests.MYTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="mytests.MYTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="mytests.MYTests">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.005" classname="mytests.MYTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MYTests.Test1(MYTests.java:21)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.005" classname="mytests.MYTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="mytests.MYTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.003" classname="mytests.MYTests">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="mytests.MYTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MYTests.Test2(MYTests.java:26)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.002" classname="mytests.MYTests"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
